name: customer_labeeny
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^2.2.0
  auto_size_text: ^2.1.0
  barcode_scan2: ^4.1.3
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^6.0.0
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0
  fluttertoast: ^8.0.7
  folding_cell: ^1.0.2
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.1.1
  get: ^4.1.4
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  google_nav_bar: ^5.0.5
  image_picker: ^0.8.0+4
  intl: ^0.17.0
  pin_code_fields: ^7.2.0
  shimmer: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
