name: delivery_boy_application
description: A new Flutter project.

publish_to: 'none' #Delete This if you want to publish to pub.dev 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^2.1.1
  auto_size_text: ^2.1.0
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.2
  dotted_line: ^3.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^6.0.0
  flutter_polyline_points: ^1.0.0
  folding_cell: ^1.0.2
  geolocator: ^7.1.0
  get: ^4.1.4
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.6
  google_nav_bar: ^5.0.3
  pin_code_fields: ^7.0.0
  qr_flutter: ^4.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/maps_icons/
    - assets/images/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
  
  
  
  
  
  
  
  
  
